export const generateInDepthContent = (title: string, context: string[]): string[] => {
    const lowerTitle = title.toLowerCase();
    
    if (lowerTitle.includes("broker") || lowerTitle.includes("platform")) {
        return [
            `Choosing the right ${title} is one of the most critical decisions in your trading career. A broker or platform isn't just a piece of software; it's your primary gateway to the global financial markets. The infrastructure provided by these entities dictates everything from your execution speed and slippage to the security of your deposited capital.`,
            `Regulation is the cornerstone of a safe trading environment. ${context[0] || 'As discussed'}, authorities such as the FCA in the UK, ASIC in Australia, and the NFA/CFTC in the United States set rigorous standards for transparency and capital adequacy. Trading with an unregulated entity is essentially gambling with your principal, as there are no legal protections if the firm disappears or engages in unethical practices.`,
            `Technological capabilities vary significantly between different providers. A professional platform should offer not just basic charting, but advanced order types like OCO (One Cancels the Other) and trailing stops. Furthermore, the underlying technology—whether it's ECN (Electronic Communication Network) or STP (Straight Through Processing)—impacts the spreads and commissions you pay on every single trade.`,
            `Customer support and educational resources are often overlooked until they are desperately needed. Because the forex market operates 24/5, your support team should be available around the clock. High-quality brokers also provide deep liquidity pools, ensuring that even during high-volatility news events, you can enter and exit positions with minimal deviation from your desired price.`,
            `Finally, the ease of deposits and withdrawals is a litmus test for a broker's integrity. While most firms make it incredibly easy to deposit funds, the true measure of a professional firm is how quickly and transparently they process withdrawal requests. Always research a firm's reputation regarding payouts before committing significant capital.`,
            `In conclusion, take your time when evaluating ${title}. Use demo accounts to test the platform's stability and the broker's execution quality. By selecting a partner that aligns with your trading style and provides a secure, low-latency environment, you lay the necessary foundation for long-term profitability and peace of mind.`
        ];
    }

    if (lowerTitle.includes("analysis") || lowerTitle.includes("technical") || lowerTitle.includes("fundamental")) {
        return [
            `The study of ${title} is what separates speculative gambling from professional trading. It is the process of extracting meaning from the chaos of market data to identify high-probability opportunities. Whether you focus on price action, economic indicators, or market sentiment, the goal remains the same: building a consistent edge over the competition.`,
            `Technical analysis, which often falls under the umbrella of ${title}, is based on the premise that all relevant information is already reflected in the price. By studying historical patterns, we look for recurring behaviors in the market's collective psychology. This approach assumes that human reactions to fear and greed are consistent across time and markets.`,
            `Fundamental analysis, on the other hand, looks at the "why" behind the move. ${context[0] || 'This involves'}, analyzing interest rates, GDP growth, and geopolitical stability. For example, a central bank's decision to raise interest rates usually strengthens its currency because it attracts foreign investment. Understanding these macro drivers allows you to position yourself for multi-week or multi-month trends.`,
            `The most successful traders often use a "top-down" approach that combines multiple layers of analysis. They might start with the fundamental outlook to determine a directional bias, then use technical levels to identify precise entry and exit points. This synergy between different schools of thought provides a much higher level of confidence in your trade setups.`,
            `However, no amount of ${title} can eliminate risk entirely. The market is a game of probabilities, not certainties. Even the most perfect fundamental and technical alignment can be disrupted by a surprise news event or a shift in sentiment. This is why every analysis-based decision must be accompanied by a robust risk management plan.`,
            `Ultimately, mastering ${title} requires practice and screen time. You must learn to filter out the noise and focus on the signals that actually move the needle. As you refine your approach, you will develop a unique perspective on the markets that allows you to remain calm and objective even in the midst of high volatility.`
        ];
    }

    return [
        `The concept of ${title} is fundamental to understanding the broader dynamics of the financial markets. While basic definitions provide a starting point, a truly professional perspective requires looking at the underlying structural forces. In this deep dive, we explore how ${title} functions within the complex ecosystem of global currency exchange and why it remains a critical focus for institutional and retail traders alike.`,
        `Historically, ${title} has evolved significantly. ${context[0] || 'As mentioned in the lesson'}, this area represents a key junction between economic policy and market sentiment. When we look at the historical data, we see that the most successful participants are those who don't just react to price movements, but understand the "why" behind them. This involves analyzing macro-economic indicators and geopolitical stability.`,
        `From a technical standpoint, ${title} interacts with other market components in subtle ways. For instance, the relationship between volume and price action often dictates the reliability of signals in this category. Professional traders often look for confluence—where multiple indicators or analysis types align—to confirm their hypotheses about ${title}. This multi-layered approach reduces risk and increases the probability of capturing significant moves.`,
        `Psychology also plays a massive role. The market is, at its heart, a collection of human decisions. Because so many traders are focused on ${title}, it can become a self-fulfilling prophecy. When a critical threshold is reached, the collective reaction of thousands of market participants can lead to explosive movements. Understanding this herd behavior allows you to anticipate turns rather than just following the crowd.`,
        `Risk management is the final, and perhaps most important, piece of the puzzle. No matter how deep your understanding of ${title}, the market can always behave unexpectedly. Professionals use strictly defined parameters to protect their capital, ensuring that no single event related to ${title} can jeopardize their long-term survival. Consistency in applying these rules is what separates the veterans from the amateurs.`,
        `In conclusion, mastering ${title} is a journey of continuous learning. As you gain more experience, you'll start to see patterns and relationships that aren't visible on the surface. By combining the foundational knowledge from this lesson with the advanced insights in this deep dive, you are well on your way to developing the "trader's intuition" that defines the world's most successful market participants.`
    ];
};
